run ~/.config/tmux/plugins/tmux-dotbar/dotbar.tmux
set -g @tmux-dotbar-bg "#060606"
set -g @tmux-dotbar-fg "#e4e4e8"
set -g @tmux-dotbar-fg-current "#ffffff"
set -g @tmux-dotbar-fg-session "#8c9cb8"
set -g @tmux-dotbar-fg-prefix "#c4a8d6"

set-option -g status-position top

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

unbind C-b
set -g prefix C-space
bind C-space send-prefix



bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind v split-window -v -c "#{pane_current_path}"
bind s split-window -h -c "#{pane_current_path}"
