run ~/.config/tmux/plugins/tmux-dotbar/dotbar.tmux
set -g @tmux-dotbar-bg "#060606"
set -g @tmux-dotbar-fg "#e4e4e8"
set -g @tmux-dotbar-fg-current "#ffffff"
set -g @tmux-dotbar-fg-session "#8c9cb8"
set -g @tmux-dotbar-fg-prefix "#c4a8d6"

set-option -g status-position top

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
