cursor            #9f9e99
cursor_text_color #101113

foreground            #9f9e99
background            #000000
selection_foreground  #e1ffe5
selection_background  #4a4253

# black
color0   #101113
color8   #4a4253

# red
color1   #93554b
color9   #93554b

# green
color2   #51606a
color10  #a7d8b0

# yellow
color3   #ac7f7b
color11  #e1ffe5

# blue
color4   #697a9a
color12  #8288A0

# magenta
color5   #83799C
color13  #997e95

# cyan
color6   #7a837c
color14  #879493

# white
color7   #9f9e99
color15  #A8A7A2
